CREATE TABLE receipt (
    receipt_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    status ENUM('PROCESSING','DONE','FAILED') DEFAULT 'PROCESSING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_receipt_user
      FOREIGN KEY (user_id) REFERENCES user(user_id)
      ON DELETE CASCADE
);
